### ISSUE TITLE
TypeError: Cannot read property 'token' of null

### ISSUE THREAD

**Issue by markknol** [ddj231/Handel#3] opened 2021-01-23 15:18 UTC
Hi there! I found your project on [twitter](https://twitter.com/algoritmic/status/1352959183436603396) and was very interested to try it out. So I tried it out locally. This is my (very basic) editor (index.html)
```html
<script src="https://unpkg.com/handel-pl"></script>
<textarea id=music style="width:100%;height:50%">
start
	chunk example using somePlayable 
		play somePlayable 
		rest for 1b
	endchunk
	save myPlayable = Eb3 for 1b
	run example using myPlayable with sound piano, loop for 5 
finish
</textarea>
<script>
function play(){
	console.log(music.value)
	Handel.RunHandel(music.value);
}
</script>
<button onclick="play()">Play</button>
```

Now I get similar errors as on the online editor, so there's something wrong here? would be nice if the error reporting was bit more specific what is wrong.

**Comment by markknol** [comment] 2021-01-23 15:25
After few other tries I noticed its the examples that result in errors.

This one (from website) doesnt work: `handel-pl:2 Uncaught (in promise) Error: error parsing input at line 1`
```
save myplayable = E4, F4, G3 for 3b
save myduration = for 1b

play myplayable
rest myduration
```
This one (from examples on github) also doesnt work: `TypeError: Cannot read property 'token' of null`
```
start
	chunk main
    	play D3, F3, G3, B3 for 1b
       	play F3, A3, C3, E3 for 1b
       	play C3, E3, G3, B3 for 1b
       	play D4, F3, G4, B3 for 1b
       	play F4, G3, B4, D3 for 1b
       	play D4, F3, G4, B3 for 1b
       	play F4, G3, B4, D3 for 1b
       	play D4, F3, G4, B3 for 1b
    endchunk
    
    chunk kickdrums 
    	play E1 for 1b
        rest for 3b
    endchunk
    
    chunk hats 
    	play E4 for 1b
    endchunk
    
    run main with sound piano, loop for 10
    run kickdrums with sound kick, loop for 20
    run hats with bpm 280, sound hihat, loop for 200
    
finish
```
When you try something random it just throws `handel-pl:2 Uncaught (in promise) Error: error analyzing input at line` but doesn't report the actual line number.

Would be great if you could look into it, I think this is a great idea.

**Comment by ddj231** [comment] 2021-01-23 17:07
@markknol thank you for submitting this issue! It seems to be a bug in the latest version of Handel v0.5.0 (which added new types). I think the issue is specific to rests. I'll look into more into this bug asap!

**Comment by ddj231** [comment] 2021-01-23 18:36
@markknol The bug is now addressed in commit d51586c. You should not come across the issue in the latest version of Handel which is now published (version 0.5.1). 

Regarding what the bug was. Rests are treated similar to plays by the Handel symbol table builder. But with rests some nodes to visit in the relevant part of the syntax tree will be null or undefined. Checks for that case were missing.

**Comment by ddj231** [comment] 2021-01-23 18:47
Additionally (looking at your follow up), some examples in the Handel documentation are full programs. But some are just code snippets rather than full programs (maybe the documentation should be changed to only include full programs). 

For example

This is not a complete Handel program because it does not have the start and finish keywords:
```
save myplayable = E4, F4, G3 for 3b
save myduration = for 1b

play myplayable
rest myduration
```


But this is:
```
start
save myplayable = E4, F4, G3 for 3b
save myduration = for 1b

play myplayable
rest myduration
finish
```

**Comment by ddj231** [comment] 2021-01-23 19:15
Lastly, you mentioned more verbose errors. The errors you mentioned were Lexer errors or errors involving invalid characters --   version (0.5.2) now adds clearer messaging for those errors (they were missing line numbers as well like you mentioned). So an invalid program like this:
```
start
*
finish
```
Would now produce an error like this: 
 ```error analyzing input at line: 2; invalid character: *```

**Closed as completed** 2021-01-25 17:41 UTC
Labels: bug

**Comment by markknol** [comment] 2021-01-26 10:30
Thanks for looking into this! 🎉 It indeed works now.
